spec-version: 0.36.0

name:                pup
version:             0.1.0
synopsis:            "Invertible format descriptors"
author:              ["Arnaud Spiwack"]
maintainer:          arnaud.spiwack@tweag.io

github: tweag/pup/pup
copyright: "(c) Modus Create LLC and its affiliates"

language: GHC2021

dependencies:
  - base >= 4.19 && < 4.22
  - comonad
  - megaparsec
  - containers
  - prettyprinter
  - text
  - stacked

library:
  source-dirs: src

tests:
  all:
    main: Test.hs
    source-dirs: test
    dependencies:
      - pup
      - hedgehog
      - mtl

ghc-options: "-Wall"
