name:                pup
version:             0.1.0
author:              ["Arnaud Spiwack"]
maintainer:          arnaud.spiwack@tweag.io
copyright:           "MIT"

language: GHC2021

dependencies:
  - base
  - comonad
  - mtl
  - megaparsec
  - containers
  - prettyprinter
  - text
  - stacked

library:
  source-dirs: src

tests:
  all:
    main: Test.hs
    source-dirs: test
    dependencies:
      - pup
      - hedgehog

ghc-options: "-Wall"
